import secondPortrait from './assets/samples/walkthrough-second.png'
import {samples} from './samples.js'
// A miniature UI illustration only. It never calls the editor or persistence.
export function renderGuideSnippet(host,step){
 const photo=`<img src="${step===4?secondPortrait:samples[0].src}" alt="" width="500" height="750">`
 const slider=`<label class="snippet-slider">Eye Enlargement <output>60</output><input type="range" min="0" max="100" value="60" aria-label="Eye Enlargement"></label>`
 const titles=['Upload photo','Eye Enlargement','Confirm preference','My Style','Apply My Style','Compare']
 const visual=step===0?`<div class="snippet-upload"><span aria-hidden="true">＋</span><button>Upload photo</button></div>`:step===3?`<div class="snippet-profile"><strong>1/5</strong><progress max="5" value="1" aria-label="Illustrated progress"></progress><span>Confirmed photos</span><div class="snippet-dots"><b>✓</b><b>2</b><b>3</b><b>4</b><b>5</b></div><p>Illustrated preference: 60</p></div>`:`<div class="snippet-photo">${photo}${step===5?`<div class="snippet-after">${photo}</div><div class="snippet-line"></div>`:''}</div>`
 host.innerHTML=`<div class="snippet"><header><strong>StyleMe</strong><span>${titles[step]}</span></header><div class="snippet-body">${visual}<div class="snippet-tools">${step===1?slider+`<label class="snippet-slider">Face Slimming <output>0</output><input type="range" min="0" max="100" value="0" aria-label="Face Slimming"></label>`:step===2?`<p>Illustrated preference: 60</p><button class="snippet-confirm">Confirm preference</button><p class="snippet-feedback" role="status"></p>`:step===4?`<p>New portrait illustration</p><button class="snippet-apply">Apply My Style</button>${slider}`:step===5?`<label>Compare<input class="snippet-divider" type="range" min="0" max="100" value="50" aria-label="Before/after divider"></label><p>Reset to Original</p><p>Download PNG</p>`:''}</div></div><footer>Illustrated simulation. No photo is edited and nothing is saved.</footer></div>`
 const range=host.querySelector('.snippet-slider input');if(range){if(step===4){range.value=0;host.querySelector('output').textContent='0'}range.oninput=()=>host.querySelector('output').textContent=range.value}
 host.querySelectorAll('.snippet-slider').forEach(label=>{label.querySelector('input').oninput=event=>label.querySelector('output').textContent=event.target.value})
 if(step===1&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const start=performance.now();range.value=30;const tick=now=>{if(!range.isConnected)return;const t=Math.min(1,(now-start)/700);range.value=Math.round(30+30*t);range.closest('label').querySelector('output').textContent=range.value;if(t<1)requestAnimationFrame(tick)};requestAnimationFrame(tick)}
 const confirm=host.querySelector('.snippet-confirm');if(confirm)confirm.onclick=()=>{host.querySelector('.snippet-feedback').textContent='Remembered ✓';host.querySelector('.snippet').classList.add('snippet-confirmed');confirm.disabled=true}
 const apply=host.querySelector('.snippet-apply');if(apply)apply.onclick=()=>{range.value=60;host.querySelector('output').textContent='60';apply.disabled=true;host.querySelector('.snippet').classList.add('snippet-confirmed')}
 const upload=host.querySelector('.snippet-upload button');if(upload)upload.onclick=()=>{host.querySelector('.snippet-upload').innerHTML=photo}
 if(step===3&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const card=host.querySelector('.snippet-profile');let count=1;const timer=setInterval(()=>{if(!card.isConnected||count===5){clearInterval(timer);return}count++;card.querySelector('strong').textContent=count+'/5';card.querySelector('progress').value=count;card.querySelectorAll('b').forEach((b,i)=>{if(i<count)b.textContent='✓'})},650)}
 const divider=host.querySelector('.snippet-divider');if(divider)divider.oninput=()=>host.querySelector('.snippet-photo').style.setProperty('--mini-split',divider.value+'%')
}
